name: hide_my_code
description: A Flutter/Dart package that allows developers to hide specific files from their repository while providing a mechanism to generate them when needed. This package provides a secure way to share code without exposing critical implementation details.
version: 1.0.0
homepage: https://github.com/AAShayon/hide_my_codes
repository: https://github.com/AAShayon/hide_my_codes

environment:
  sdk: ^3.0.0

executables:
  hide_my_code:

dependencies:
  args: ^2.4.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  path: ^1.8.3
  flutter_dotenv: ^5.2.1
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0