name: hide_my_code
description: Hide and encrypt files in your repository with password protection.
version: 1.0.1
homepage: https://github.com/AAShayon/hide_my_codes
repository: https://github.com/AAShayon/hide_my_codes

environment:
  sdk: ^3.0.0

executables:
  hide_my_code:

dependencies:
  args: ^2.4.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  path: ^1.8.3
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0